"""initial schema

Revision ID: 106b7f46bd3d
Revises: 
Create Date: 2026-04-09 14:54:03.531497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106b7f46bd3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('collection', 'hub', 'market', name='agentrole'), nullable=False),
    sa.Column('location_name', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('route_name', sa.String(length=120), nullable=False),
    sa.Column('origin_town', sa.String(length=80), nullable=False),
    sa.Column('destination_town', sa.String(length=80), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracking_code', sa.String(length=20), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('fee_rwf', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'in_transit', 'at_hub', 'out_for_delivery', 'awaiting', 'collected', name='parcelstatus'), nullable=True),
    sa.Column('collection_agent_id', sa.String(), nullable=False),
    sa.Column('market_agent_id', sa.String(), nullable=True),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_tracking_code'), 'parcels', ['tracking_code'], unique=True)
    op.create_table('parcel_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_events_parcel_id'), 'parcel_events', ['parcel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_events_parcel_id'), table_name='parcel_events')
    op.drop_table('parcel_events')
    op.drop_index(op.f('ix_parcels_tracking_code'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('trips')
    op.drop_table('agents')
    op.drop_table('agencies')
    # ### end Alembic commands ###
